import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "myapp",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "./fonts/Pretendard-Regular.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center w-full">
          <div className="w-[360px] border-x">
            <div className="w-full h-[55px]"></div>
            <div className={myFont.className}>{children} </div>
          </div>
        </div>
      </body>
    </html>
  );
}
